const x = 1 + 2;

const a = {
  'Prettier-SQL.SQLFlavourOverride': 'postgresql',
  'Prettier-SQL.expressionWidth': 80,
  'Prettier-SQL.keywordCase': 'lower',
  'Prettier-SQL.tabSizeOverride': 4,
  '[css]': {
    'editor.defaultFormatter': 'esbenp.prettier-vscode',
  },
  '[github-actions-workflow]': {
    'editor.tabSize': 2,
    'editor.defaultFormatter': 'redhat.vscode-yaml',
  },
  '[html]': {
    'editor.defaultFormatter': 'esbenp.prettier-vscode',
  },
  '[javascript]': {
    'editor.defaultFormatter': 'esbenp.prettier-vscode',
  },
  '[json-tmlanguage]': {
    'editor.tabSize': 2,
  },
  '[json]': {
    'editor.defaultFormatter': 'esbenp.prettier-vscode',
    'editor.fontLigatures': false,
    'editor.tabSize': 2,
  },
  '[jsonc]': {
    'editor.defaultFormatter': 'vscode.json-language-features',
    'editor.fontLigatures': false,
    'editor.tabSize': 2,
  },
  '[markdown]': {
    'editor.defaultFormatter': 'DavidAnson.vscode-markdownlint',
    'editor.fontLigatures': false,
    'editor.tabSize': 2,
  },
  '[plaintext]': {
    'editor.acceptSuggestionOnCommitCharacter': false,
    'editor.acceptSuggestionOnEnter': 'off',
    'editor.fontLigatures': false,
    'editor.suggest.showSnippets': false,
    'editor.suggest.showWords': false,
    'editor.tabSize': 2,
  },
  '[python]': {
    'editor.defaultFormatter': 'ms-python.autopep8',
  },
  '[typescript]': {
    'editor.defaultFormatter': 'esbenp.prettier-vscode',
  },
  '[typescriptreact]': {
    'editor.defaultFormatter': 'esbenp.prettier-vscode',
  },
  '[xml]': {
    'editor.tabSize': 2,
    'editor.defaultFormatter': 'redhat.vscode-xml',
    'editor.fontLigatures': false,
  },
  '[yaml-tmlanguage]': {
    'editor.tabSize': 2,
  },
  '[yaml]': {
    'editor.defaultFormatter': 'esbenp.prettier-vscode',
    'editor.tabSize': 2,
  },
  'aicommit.model': 'mistralai/mistral-small-24b-instruct-2501:free',
  'aicommit.provider': 'openrouter',
  'antlr4.format': {
    alignActions: true,
    alignColons: 'none',
    alignFirstTokens: false,
    alignLabels: true,
    alignLexerCommands: true,
    alignSemicolons: 'none',
    alignTrailers: true,
    alignTrailingComments: true,
    allowShortBlocksOnASingleLine: true,
    allowShortRulesOnASingleLine: true,
    breakBeforeBraces: false,
    breakBeforeParens: false,
    columnLimit: 120,
    continuationIndentWidth: 4,
    groupedAlignments: true,
    indentWidth: 4,
    keepEmptyLinesAtTheStartOfBlocks: false,
    maxEmptyLinesToKeep: 1,
    minEmptyLines: 0,
    reflowComments: false,
    ruleInternalsOnSingleLine: false,
    singleLineOverrulesHangingColon: false,
    spaceBeforeAssignmentOperators: true,
    tabWidth: 4,
    useTab: false,
  },
  'autopep8.args': ['--experimental', '--max-line-length=130'],
  'clang-tidy.checks': [
    '*',
    '-altera*',
    '-android*',
    '-bugprone-assignment-in-if-condition',
    '-bugprone-inc-dec-in-conditions',
    '-cert-*-cpp',
    '-cert-err33-c',
    '-clang-analyzer-cplusplus*',
    '-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling',
    '-clang-analyzer-valist.Uninitialized',
    '-concurrency-mt-unsafe',
    '-cppcoreguidelines*',
    '-google-readability-braces-around-statements',
    '-google-readability-function-size',
    '-hicpp*',
    '-linuxkernel*',
    '-llvm-header-guard',
    '-llvmlibc-restrict-system-libc-headers',
    '-modernize*',
    '-readability-avoid-nested-conditional-operator',
    '-readability-braces-around-statements',
    '-readability-enum-initial-value',
    '-readability-function-cognitive-complexity',
    '-readability-function-size',
    '-readability-identifier-length',
    '-readability-implicit-bool-conversion',
    '-readability-isolate-declaration',
    '-readability-magic-numbers',
    '-readability-math-missing-parentheses',
    '-misc-no-recursion',
  ],
  'clang-tidy.lintOnSave': false,
  'clangd.arguments': ['--header-insertion=never', '--clang-tidy'],
  'clangd.checkUpdates': true,
  'cody.chat.defaultLocation': 'editor',
  'cody.commandCodeLenses': false,
  'cody.suggestions.mode': 'off',
  'cody.telemetry.level': 'off',
  'csharp.debug.symbolOptions.searchMicrosoftSymbolServer': true,
  'csharp.debug.symbolOptions.searchNuGetOrgSymbolServer': true,
  'css.format.maxPreserveNewLines': 1,
  'css.format.spaceAroundSelectorSeparator': true,
  'debug.onTaskErrors': 'showErrors',
  'debugpy.debugJustMyCode': false,
  'diffEditor.codeLens': true,
  'diffEditor.ignoreTrimWhitespace': false,
  'dotnet.automaticallyCreateSolutionInWorkspace': false,
  'dotnet.formatting.organizeImportsOnFormat': true,
  'dotnet.typeMembers.propertyGenerationBehavior': 'preferAutoProperties',
  'dotnetAcquisitionExtension.enableTelemetry': false,
  'doxdocgen.c.commentPrefix': '/// ',
  'doxdocgen.c.firstLine': '',
  'doxdocgen.c.lastLine': '',
  'doxdocgen.c.triggerSequence': '///',
  'doxdocgen.file.copyrightTag': [],
  'doxdocgen.file.fileTemplate': '@file',
  'doxdocgen.file.versionTag': '',
  'doxdocgen.generic.authorEmail': '',
  'doxdocgen.generic.authorName': 'Scover',
  'doxdocgen.generic.authorTag': '@author ',
  'doxdocgen.generic.boolReturnsTrueFalse': true,
  'doxdocgen.generic.commandSuggestion': true,
  'doxdocgen.generic.commandSuggestionAddPrefix': true,
  'doxdocgen.generic.dateFormat': 'DD/MM/YYYY',
  'doxdocgen.generic.returnTemplate': '@return ',
  'doxdocgen.generic.useGitUserName': true,
  'editor.detectIndentation': false,
  'editor.fontFamily': 'JetBrains Mono',
  'editor.fontLigatures': true,
  'editor.inlayHints.enabled': 'off',
  'editor.inlineSuggest.suppressSuggestions': true,
  'editor.lineHeight': 1.6,
  'editor.minimap.enabled': false,
  'editor.renderWhitespace': 'all',
  'editor.scrollBeyondLastLine': false,
  'editor.semanticTokenColorCustomizations': {
    enabled: true,
    rules: {
      comment: '#ff8c00',
    },
  },
  'editor.tokenColorCustomizations': {
    comments: '#ff8c00',
    textMateRules: [
      {
        scope: [
          'comment.block.documentation',
          'comment.documentation',
          'comment.line.double-slash.documentation',
          'punctuation.definition.comment.begin.documentation',
          'punctuation.definition.comment.documentation',
          'punctuation.definition.comment.end.documentation',
        ],
        settings: {
          foreground: '#6A9955',
        },
      },
    ],
  },
  'editor.unicodeHighlight.invisibleCharacters': false,
  'editor.wordWrap': 'on',
  'editor.wordWrapColumn': 120,
  'emmet.excludeLanguages': [],
  'emmet.includeLanguages': {
    markdown: 'html',
  },
  'emmet.preferences': {
    'css.color.short': true,
    'profile.allowCompactBoolean': true,
  },
  'eslint.format.enable': true,
  'eslint.lintTask.enable': true,
  'eslint.useESLintClass': true,
  'eslint.useFlatConfig': true,
  'eslint.validate': ['typescript', 'javascript'],
  'explorer.confirmDelete': false,
  'explorer.confirmDragAndDrop': false,
  'explorer.confirmPasteNative': false,
  'files.associations': {
    '*.cppm': 'cpp',
    '*.css': 'css',
    '*.ebnf': 'ebnf',
    '*.em': 'plaintext',
    '*.h': 'c',
    '*.jsonf': 'plaintext',
    '*.latax': 'latex',
    '*.mdq': 'plaintext',
    '.htaccess': 'plaintext',
    '.jslave': 'plaintext',
    Doxyfile: 'ini',
    LICENSE: 'plaintext',
  },
  'files.autoSave': 'onFocusChange',
  'files.exclude': {
    '**/__pycache__/': true,
    '**/node_modules/': true,
    'venv/': true,
  },
  'formatFiles.excludePattern': '**/*.pdf,**/.git,**/*.png,**/*.jpg,**/*.svg,**/__pycache__,**/*.webp,**/*.csv',
  'formatFiles.runOrganizeImports': true,
  'fracturedjsonvsc.v3.MaxTotalLineLength': 120,
  'fracturedjsonvsc.v3.StringWidthPolicy': 'CharacterCount',
  'git.autofetch': true,
  'git.blame.statusBarItem.enabled': false,
  'git.confirmSync': false,
  'git.enableSmartCommit': true,
  'git.ignoreRebaseWarning': true,
  'git.openRepositoryInParentFolders': 'always',
  'gitlens.ai.generateCommitMessage.enabled': false,
  'gitlens.graph.minimap.additionalTypes': ['localBranches', 'stashes', 'remoteBranches', 'pullRequests', 'tags'],
  'html.format.maxPreserveNewLines': 1,
  'html.format.templating': true,
  'html.format.wrapLineLength': 0,
  'javascript.format.semicolons': 'insert',
  'javascript.inlayHints.functionLikeReturnTypes.enabled': true,
  'javascript.inlayHints.parameterNames.enabled': 'all',
  'javascript.preferences.quoteStyle': 'single',
  'javascript.preferences.useAliasesForRenames': false,
  'javascript.referencesCodeLens.enabled': true,
  'javascript.referencesCodeLens.showOnAllFunctions': true,
  'javascript.suggest.completeFunctionCalls': true,
  'javascript.updateImportsOnFileMove.enabled': 'always',
  'less.format.maxPreserveNewLines': 1,
  'liveSassCompile.settings.formats': [
    {
      extensionName: '.css',
      format: 'expanded',
      savePath: null,
      savePathReplacementPairs: null,
    },
  ],
  'liveSassCompile.settings.showOutputWindowOn': 'Warning',
  'liveSassCompile.settings.useNewCompiler': true,
  'liveServer.settings.donotShowInfoMsg': true,
  'liveServer.settings.donotVerifyTags': true,
  'lldb.showDisassembly': 'never',
  'makefile.configureOnOpen': true,
  'markdown-code-block-formatter.defaultLanguage': 'text',
  'markdown-code-block-formatter.languageNameMapping': {
    js: 'javascript',
  },
  'markdown.extension.print.absoluteImgPath': false,
  'markdown.extension.print.theme': 'dark',
  'markdown.extension.toc.levels': '2..6',
  'markdown.math.enabled': false,
  'markdown.occurrencesHighlight.enabled': true,
  'markdown.preview.lineHeight': 2,
  'markdown.preview.typographer': true,
  'markdownlint.config': {
    MD046: false,
    MD026: false,
    MD004: {
      style: 'dash',
    },
    MD024: {
      siblings_only: true,
    },
    MD028: false,
    MD029: false,
    MD033: false,
    MD036: false,
    MD055: false,
    MD056: false,
    MD010: false,
  },
  'mesonbuild.downloadLanguageServer': true,
  'notebook.lineNumbers': 'on',
  'omnisharp.loggingLevel': 'warning',
  'pgFormatter.functionCase': 'lowercase',
  'pgFormatter.keepNewline': true,
  'pgFormatter.keywordCase': 'lowercase',
  'pgFormatter.spaces': 4,
  'php.completion.autoimport-docblock': 'default',
  'php.completion.namingConvention': 'snake_case',
  'php.completion.parameters': 'parameters',
  'php.completion.showParameters': true,
  'php.format.rules.indentHeredoc': true,
  'php.format.rules.inlineHeredoc': true,
  'php.inlayHints.parameters.enabled': false,
  'php.inlayHints.types.variable': true,
  'php.problems.exclude': {
    '/': ['PHP2424', 'PHP2439', 'PHP6612', 'PHP6611'],
  },
  'php.suggest.basic': false,
  'php.validate.enable': false,
  'php.workspace.shortOpenTag': 'false',
  'prettier.arrowParens': 'avoid',
  'prettier.jsxSingleQuote': true,
  'prettier.printWidth': 120,
  'prettier.singleQuote': true,
  'pretty-php.formatting.alignment.alignChains': true,
  'pretty-php.formatting.alignment.alignComments': true,
  'pretty-php.formatting.alignment.alignData': true,
  'pretty-php.formatting.heredocIndentation': 'none',
  'pretty-php.formatting.operatorPlacement': 'first',
  'pretty-php.formatting.preserveOneLineStatements': true,
  'python.analysis.autoImportCompletions': true,
  'python.analysis.completeFunctionParens': true,
  'python.analysis.supportDocstringTemplate': true,
  'python.analysis.typeCheckingMode': 'standard',
  'python.analysis.typeEvaluation.deprecateTypingAliases': true,
  'python.analysis.typeEvaluation.enableReachabilityAnalysis': true,
  'python.analysis.typeEvaluation.strictDictionaryInference': true,
  'python.analysis.typeEvaluation.strictListInference': true,
  'python.analysis.typeEvaluation.strictSetInference': true,
  'python.missingPackage.severity': 'Warning',
  'python.terminal.shellIntegration.enabled': true,
  'robot.completions.keywords.argumentsSeparator': '  ',
  'scss.format.maxPreserveNewLines': 1,
  'scss.format.spaceAroundSelectorSeparator': true,
  'scss.lint.float': 'warning',
  'shellcheck.customArgs': ['-x'],
  'sort-json.settings.customSortComparisons': [
    {
      comparison:
        'isObject ? typeof item1 === typeof item2 ? key1.localeCompare(key2) : (typeof item1).localeCompare(typeof item2) : true',
      description: 'sort by type then by name',
    },
  ],
  'sort-json.settings.isCaseSensitive': true,
  'sort-json.settings.objectSortType': 'Key',
  'sort-json.settings.sortMode': 'Objects Only',
  'terminal.integrated.defaultProfile.linux': 'bash',
  'terminal.integrated.enableMultiLinePasteWarning': 'never',
  'terminal.integrated.useWslProfiles': false,
  'typescript.format.semicolons': 'insert',
  'typescript.implementationsCodeLens.enabled': true,
  'typescript.implementationsCodeLens.showOnInterfaceMethods': true,
  'typescript.inlayHints.parameterNames.enabled': 'all',
  'typescript.locale': 'en',
  'typescript.preferences.useAliasesForRenames': false,
  'typescript.referencesCodeLens.enabled': true,
  'typescript.referencesCodeLens.showOnAllFunctions': true,
  'typescript.suggest.completeFunctionCalls': true,
  'typescript.surveys.enabled': false,
  'typescript.tsserver.log': 'off',
  'typescript.updateImportsOnFileMove.enabled': 'always',
  'vscode-ssh-config-enhanced.format.indentSize': 4,
  'window.commandCenter': false,
  'window.confirmSaveUntitledWorkspace': false,
  'workbench.colorCustomizations': {
    'statusBar.background': '#1F1F1F',
    'statusBar.debuggingBackground': '#1F1F1F',
    'statusBar.noFolderBackground': '#1F1F1F',
  },
  'workbench.colorTheme': 'Monokai',
  'workbench.commandPalette.experimental.suggestCommands': true,
  'workbench.startupEditor': 'none',
  'zig.zls.enabled': 'on',
  'zig.zls.inlayHintsHideRedundantParamNames': true,
  'zig.zls.inlayHintsHideRedundantParamNamesLastToken': true,
  'zig.zls.inlayHintsShowVariableTypeHints': false,
  'zig.zls.skipStdReferences': true,
  'zig.zls.warnStyle': true,
  'github.copilot.chat.localeOverride': 'en',
  'regExpSaver.saved': [
    {
      label: 'Remove bold from Markdown headings',
      regExp: '^(#{1,6} .*?)\\*\0\\*(.+)\\*\\*',
      regExpFlags: 'gm',
      replacePattern: '$1$2',
    },
    {
      label: 'Remove Markdown bold',
      regExp: '\\*\\*(.+?)\\*\\*',
      regExpFlags: 'gm',
      replacePattern: '$1',
    },
    {
      label: 'Unicode double quotes to ASCII',
      regExp: '[“”]',
      regExpFlags: 'gm',
      replacePattern: '"',
    },
    {
      label: 'Unicocde single quotes to ASCII',
      regExp: '’',
      regExpFlags: 'gm',
      replacePattern: "'",
    },
    {
      label: 'Decrement Markdown headings',
      regExp: '^#(#{1,5} \\S)',
      regExpFlags: 'gm',
      replacePattern: '$1',
    },
    {
      label: 'Remove horizontal rules',
      regExp: '\\n?^-{3,}$\\n?',
      regExpFlags: 'gm',
      replacePattern: '',
    },
    {
      label: 'Increment Markdown headings',
      regExp: '(^#{1,5} )',
      replacePattern: '#$1',
      regExpFlags: 'gm',
    },
    {
      label: 'Remove empty lines in nested lists',
      regExp: '\\n(\\n\\s+[*-])',
      replacePattern: '$1',
    },
  ],
  'editor.acceptSuggestionOnEnter': 'off',
  'cSpell.ignoreRegExpList': ['/`[^`]*`/', '/```[\\s\\S]*?```/', 'proper-noun'],
  'cSpell.caseSensitive': true,
  'cSpell.userWords': [
    'ANTLR',
    'electrolyzer',
    'Esolang',
    'github',
    'infonode',
    'infonodes',
    'initializers',
    'interpretability',
    'Keybinds',
    'millibuckets',
    'Moodle',
    'Nonogram',
    'Nonograms',
    'nullable',
    'oeuil',
    'persulfate',
    'powderbarrel',
    'pytest',
    'rabbids',
    'Scover',
    'trinitrate',
  ],
  'cSpell.enabledFileTypes': {
    '*': false,
    plaintext: true,
  },
  'cSpell.ignorePaths': [
    'package-lock.json',
    'node_modules',
    'vscode-extension',
    '.git/{info,lfs,logs,refs,objects}/**',
    '.git/{index,*refs,*HEAD}',
    '.vscode',
    '.vscode-insiders',
    'Pipfile',
    'Pipfile.lock',
    'tox.ini',
    'requirements_dev.txt',
    'requirements.txt',
    'pyproject.toml',
  ],
  'github.copilot.chat.agent.autoFix': false,
  'cSpell.language': 'en,fr',
  'VSCodeCounter.exclude': ['**/.gitignore', '**/.vscode/**', '**/node_modules/**', 'package-lock.json'],
  'workbench.secondarySideBar.defaultVisibility': 'hidden',
  'editor.inlineSuggest.edits.showCollapsed': true,
  'python.analysis.importFormat': 'relative',
  'python.analysis.logLevel': 'Warning',
  'formatFiles.logLevel': 'warn',
  'cSpell.diagnosticLevel': 'Hint',
  'telemetry.feedback.enabled': false,
  'github.copilot.nextEditSuggestions.enabled': true,
  'insertDateString.format': '**MM-DD-YY hh:mm**',
  'rainbow_csv.rbql_with_headers_by_default': true,
  'workbench.sideBar.location': 'right',
  'terminal.integrated.defaultProfile.windows': 'bash (MSYS2)',
  'git.ignoreMissingGitWarning': true,
  'shellformat.effectLanguages': [
    'shellscript',
    'dockerfile',
    'dotenv',
    'hosts',
    'jvmoptions',
    'ignore',
    'gitignore',
    'properties',
    'spring-boot-properties',
    'azcli',
    'bats',
  ],
  'shellformat.useEditorConfig': true,
  'terminal.integrated.shellIntegration.enabled': false,
  'editor.stickyTabStops': true,
  'task.allowAutomaticTasks': 'on',
  'rainbow_csv.virtual_alignment_vertical_grid': true,
  '[dockercompose]': {
    'editor.insertSpaces': true,
    'editor.tabSize': 2,
    'editor.autoIndent': 'advanced',
    'editor.defaultFormatter': 'redhat.vscode-yaml',
  },
  'terminal.integrated.profiles.linux': {
    bash: {
      path: 'bash',
      icon: 'terminal-bash',
    },
    zsh: {
      path: 'zsh',
    },
    fish: {
      path: 'fish',
    },
    tmux: {
      path: 'tmux',
      icon: 'terminal-tmux',
    },
    pwsh: {
      path: 'pwsh',
      icon: 'terminal-powershell',
    },
  },
  'terminal.integrated.profiles.windows': {
    'bash (MSYS2)': {
      path: 'E:\\Program Files\\msys2\\usr\\bin\\bash.exe',
      args: ['--login', '-i'],
      env: {
        CHERE_INVOKING: '1',
        MSYSTEM: 'UCRT64',
      },
      icon: 'terminal-bash',
    },
    PowerShell: {
      source: 'PowerShell',
      icon: 'terminal-powershell',
    },
    'Command Prompt': {
      path: ['${env:windir}\\Sysnative\\cmd.exe', '${env:windir}\\System32\\cmd.exe'],
      args: [],
      icon: 'terminal-cmd',
    },
    'Git Bash': {
      source: 'Git Bash',
      icon: 'git-commit',
    },
  },
  'cSpell.validateDirectives': true,
  'cSpell.patterns': [
    {
      name: 'proper-noun',
      pattern: '/\\b\\p{Lu}[\\p{Ll}\\d][\\p{L}\\d]*\\b/gu',
    },
  ],
  'xml.fileAssociations': [
    {
      pattern: 'ControlManifest.Input.xml',
      systemId: 'C:/Users/DJ6664/Repos/njpcf/schemas/ControlManifest.Input.xsd',
    },
  ],
  'sort-json.settings.defaultCustomSort': '',
  'sort-json.settings.promptCollectionKeys': true,
  'testing.automaticallyOpenPeekView': 'failureInVisibleDocument',
  'explorer.sortOrder': 'filesFirst',
  'github.copilot.enable': {
    '*': false,
    plaintext: false,
    markdown: false,
    scminput: false,
  },
  'editor.accessibilitySupport': 'off',
  'npm.packageManager': 'pnpm',
  'npm.scriptRunner': 'pnpm',
  'stylelint.packageManager': 'pnpm',
  'terminal.integrated.stickyScroll.enabled': false,
  'fracturedjsonvsc.MaxTotalLineLength': 120,
  'fracturedjsonvsc.StringWidthPolicy': 'CharacterCount',
  'gitlens.ai.model': 'vscode',
  'gitlens.ai.vscode.model': 'copilot:gpt-4.1',
  '[scss]': {
    'editor.defaultFormatter': 'esbenp.prettier-vscode',
  },
  '[mdx]': {
    'editor.defaultFormatter': 'esbenp.prettier-vscode',
  },
  'vscode-wordcount-leeopop.defaultDocumentToggle': false,
  'chat.mcp.gallery.enabled': true,
  'markdown.preview.breaks': true,
  'vscodemacros.macroFilePath': '{INSTAL}/scripts/vscode-macros.js',
  '[astro]': {
    'editor.defaultFormatter': 'astro-build.astro-vscode',
  },
  'svgPreview.autoOpen': false,
  'yaml.format.trailingComma': false,
  'astro.updateImportsOnFileMove.enabled': true,
  'lit-html.tags': ['html', 'raw', 'jsx'],
  'yaml.schemaStore.enable': false,
  'editor.formatOnSave': true,
  'gitlens.views.scm.grouped.views': {
    commits: true,
    branches: true,
    remotes: true,
    stashes: true,
    tags: true,
    worktrees: true,
    contributors: true,
    fileHistory: false,
    repositories: true,
    searchAndCompare: true,
    launchpad: false,
  },
  'explorer.fileNesting.enabled': true,
  'markdown-pdf-plus.CSSPath': '/home/raphael/Documents/repos/instal/markdown-css/modest.css',
  'bun.runtime': '/home/raphael/.bun/bin/bun',
  'files.insertFinalNewline': true,
  'remote.autoForwardPorts': false,
  'prettier.useEditorConfig': false,
};
